### PR TITLE
Testing of my first assignment.

### PR DESCRIPTION
**Pull request by paujamadar1**
Please review, I have created new Login Test class for further Login scripting.

### CODE REVIEW

**Review by indrayani2024 — CHANGES_REQUESTED** [review]
@paujamadar1 add one more test case.

**Comment by paujamadar1** [comment]
Changes has been done, Please review now and approve if possible or else please suggest any changes

**Review by indrayani2024 — APPROVED** [review]
Looks good. Approved.

**Review by PriyankaJadhav8998 — APPROVED** [review]
Looks good you can go for merge.

**Pull request merged**
